version: '2'

services:

  glbd:
    image: pierredavidbelanger/glbd:1.0.1.1
    ports:
      - '8080:8080'
    command: --round --threads 2 --control 0.0.0.0:4444 8080

  zdlb:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
